<?xml version="1.0"?>
<definitions name="Workstation" targetNamespace="urn:Workstation" xmlns:tns="urn:Workstation"  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:article">
      <xsd:element name="getName" type="xsd:string" />
	  <xsd:element name="ArticleResponse" type="xsd:string" />	 	  
	</xsd:schema>			
  </types>
  
  <message name="findArticle">
    <part name="yourName" type="tns:getName" />
  </message>
  
  <message name="findArticleResponse">
    <part name="return" type="tns:ArticleResponse"/>
  </message>  
  
  <portType name="ArticlePort">
    <operation name="findArticle">
	  <input message="tns:findArticle" />
	  <output message="tns:findArticleResponse" />
	</operation>
  </portType>
  
  <binding name="ArticleBinding" type="tns:ArticlePort">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
	  <operation name="findArticle">
	    <soap:operation soapAction="urn:ArticleAction" />
		<input>
		  <soap:body use="encoded" namespace="urn:article" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />		  
		</input>
		<output>
		  <soap:body use="encoded" namespace="urn:article" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />		  
		</output>
	  </operation>
  </binding>
  
  <service name="ArticleService">
    <port name="ArticlePort" binding="tns:ArticleBinding">
	  <soap:address location="http://localhost/rnwa/server.php" /> 
	</port>
  </service>
    
</definitions>